---
# defaults file for patch-operator-deploy
argo_project: default
repo_url: https://github.com/isma-aguilera/ansible-patch-operator-deploy
repo_path: rendered
repo_revision: main
destination_namespace: patch-operator

# subscrition
channel: alpha
source: community-operators
namespace: openshift-gitops
release_name: patch-operator
operator_name: patch-operator
source_namespace: openshift-marketplace
Approval: Manual

